import jakarta.mail.*;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import java.util.*;

public class TestSmtp {
    public static void main(String[] args) {
        System.out.println("🧪 Testing SMTP connection to Mailpit...");
        
        Properties props = new Properties();
        props.put("mail.smtp.host", "localhost");
        props.put("mail.smtp.port", "1025");
        props.put("mail.smtp.auth", "false");
        props.put("mail.smtp.starttls.enable", "false");
        props.put("mail.smtp.ssl.enable", "false");
        
        try {
            Session session = Session.getInstance(props);
            MimeMessage message = new MimeMessage(session);
            
            message.setFrom(new InternetAddress("sms-relay@test.com"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse("test@example.com"));
            message.setSubject("📱 SMS Relay Test - " + new Date());
            message.setText("🎉 SMS-Email Gateway Test Successful!\n\n" +
                          "📱 From: +8613800138000\n" +
                          "⏰ Time: " + new Date() + "\n" +
                          "💬 Message: Test SMS forwarding functionality\n\n" +
                          "🔧 Configuration:\n" +
                          "• SMTP Host: localhost:1025 (Mailpit)\n" +
                          "• Auth: Disabled (test mode)\n" +
                          "• SSL/TLS: Disabled (local testing)\n\n" +
                          "🚀 The SMS-to-Email gateway is working correctly!\n\n" +
                          "Generated by SMS Email Gateway v1.0.0");
            
            Transport.send(message);
            System.out.println("✅ Email sent successfully!");
            System.out.println("📧 Check Mailpit at: http://localhost:8025");
            
        } catch (Exception e) {
            System.out.println("❌ SMTP test failed: " + e.getMessage());
            e.printStackTrace();
        }
    }
}