#!/usr/bin/env kotlin

@file:DependsOn("com.sun.mail:jakarta.mail:2.0.1")
@file:DependsOn("com.sun.activation:jakarta.activation:2.0.1")

import jakarta.mail.*
import jakarta.mail.internet.InternetAddress
import jakarta.mail.internet.MimeMessage
import java.util.*

fun testSMTP() {
    println("🧪 Testing SMTP connection to Mailpit...")
    
    val props = Properties().apply {
        put("mail.smtp.host", "localhost")
        put("mail.smtp.port", "1025")
        put("mail.smtp.auth", "false")
        put("mail.smtp.starttls.enable", "false")
        put("mail.smtp.ssl.enable", "false")
    }
    
    try {
        val session = Session.getInstance(props)
        val message = MimeMessage(session).apply {
            setFrom(InternetAddress("sms-relay@test.com"))
            setRecipients(Message.RecipientType.TO, InternetAddress.parse("test@example.com"))
            subject = "📱 SMS Relay Test - ${Date()}"
            setText("""
                🎉 SMS-Email Gateway Test Successful!
                
                📱 From: +8613800138000
                ⏰ Time: ${Date()}
                💬 Message: Test SMS forwarding functionality
                
                🔧 Configuration:
                • SMTP Host: localhost:1025 (Mailpit)
                • Auth: Disabled (test mode)
                • SSL/TLS: Disabled (local testing)
                
                🚀 The SMS-to-Email gateway is working correctly!
                
                Generated by SMS Email Gateway v1.0.0
            """.trimIndent())
        }
        
        Transport.send(message)
        println("✅ Email sent successfully!")
        println("📧 Check Mailpit at: http://localhost:8025")
        
    } catch (e: Exception) {
        println("❌ SMTP test failed: ${e.message}")
        e.printStackTrace()
    }
}

testSMTP()