steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: NOM_DE_TON_DOSSIER # Remplace par le nom du dossier

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        working-directory: NOM_DE_TON_DOSSIER # Remplace ici aussi
